### ISSUE TITLE
Deploy this app automatically to Heroku?

### ISSUE THREAD

**Issue by Cantido** [indentlabs/dactyl#18]
I notice you have this app running on Heroku. Since I love automation I have Travis deploying my own Rails app to my Heroku domain. It's super easy. Want to give that a try?

Here's my app's [.travis.yml](https://github.com/Cantido/toaster/blob/master/.travis.yml), in the `deploy` section you can see that it isn't hard to set up. In fact, travis's gem can set this up for you automatically, encrypting your deploy token and everything.

**Comment by drusepth** [comment]
I'd be down to give it a try. That'd be pretty awesome to have set up.

**Comment by Cantido** [comment]
It's easy, if you install the Travis gem and log into it, you can just do a
command like `travis heroku` and it does everything for you.

**Comment by Cantido** [comment]
Correction, it would be `travis setup heroku`, here are Travis's docs on it: https://docs.travis-ci.com/user/deployment/heroku

**Comment by drusepth** [comment]
```
dactyl · master± ⟩ travis-1.8.0/bin/travis setup heroku
Detected repository as indentlabs/dactyl, is this correct? |yes| y
Deploy only from indentlabs/dactyl? |yes| y
Encrypt API key? |yes| y
dactyl · master± ⟩
```

And I see you've already made the change to `travis.yml`, so we should be good. :)

**Comment by Cantido** [comment]
That's correct, the build is all set to add a deployment.

**Comment by drusepth** [comment]
Just a heads up on this: the other IL project I'm actively working on right now (also on Heroku) is hitting their upper DB size resource limits, so I'm probably going to move it over to EC2. It's probably not going to need the whole box, so it probably makes sense to move this (and indentapp.com) over to the same box. 

Not sure if this changes this issue; just wanted to give a heads up of that. If we can't do CI deployments there (or if it's hard / not worth it), I don't mind leaving this project on Heroku for a while, though. It'd just be nice to get rid of the mandatory sleep times Heroku enforces on its free tier.

**Comment by Cantido** [comment]
We can script anything, even if Travis doesn't have a plugin for it, you could write straight bash in the config file. I'm not familiar with amazon services but I know that Travis has an S3 plugin.
